### ISSUE TITLE
Replace deprecated item metadata functions

### ISSUE THREAD

**Issue by OgelGames** [OgelGames/powerbanks#7]
Use `ItemStack:get_meta()` instead of deprecated `ItemStack:get_metadata()` and `ItemStack:set_metadata()` functions.

**Comment by OgelGames** [comment]
Also adapt to change in technic plus: https://github.com/mt-mods/technic/pull/233

**Comment by S-S-X** [comment]
This would be one good test case, of course good to update but I mean it should work without any changes.
If powerbanks break because of using deprecated functions then there's something wrong with technic pr.
(there's a lot of other tools that should work after technic update)
